<?php
//  ------------------------------------------------------------------------ //
//                XOOPS - PHP Content Management System                      //
//                    Copyright (c) 2000 XOOPS.org                           //
//                       <http://www.xoops.org/>                             //
//  ------------------------------------------------------------------------ //
//  This program is free software; you can redistribute it and/or modify     //
//  it under the terms of the GNU General Public License as published by     //
//  the Free Software Foundation; either version 2 of the License, or        //
//  (at your option) any later version.                                      //
//                                                                           //
//  You may not change or alter any portion of this comment or credits       //
//  of supporting developers from this source code or any supporting         //
//  source code which is considered copyrighted (c) material of the          //
//  original comment or credit authors.                                      //
//                                                                           //
//  This program is distributed in the hope that it will be useful,          //
//  but WITHOUT ANY WARRANTY; without even the implied warranty of           //
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            //
//  GNU General Public License for more details.                             //
//                                                                           //
//  You should have received a copy of the GNU General Public License        //
//  along with this program; if not, write to the Free Software              //
//  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA //
//  ------------------------------------------------------------------------ //
// Author:    Ashley Kitson                                                  //
// Copyright: (c) 2004, Ashley Kitson                                        //
// URL:       http://xoobs.net                                               //
// Project:   The XOOPS Project (http://www.xoops.org/)                      //
// Module:    XBS MetaTags (TAGS)                                            //
// ------------------------------------------------------------------------- //
/**
* Module installation parameters 
*
* This script conforms to the Xoops standard for xoops_version.php
*
* @author Ashley Kitson http://xoobs.net
* @copyright 2005 Ashley Kitson, UK
* @package TAGS
* @subpackage Installation
* @access private
* @version 1
*/

/**
 * XBS TAGS non langaue specific constant definitions
 */
include_once(XOOPS_ROOT_PATH."/modules/xbs_tags/include/defines.php");

$modversion['name'] = _MI_TAGS_NAME;
$modversion['version'] = 1.0;
$modversion['description'] = _MI_TAGS_DESC;
$modversion['credits'] = "Ashley Kitson<br />( http://xoobs.net/ )<br>Hervé Thouzard />(http://www.herve-thouzard.com)";
$modversion['author'] = "Ashley Kitson";
$modversion['help'] = "addrhelp.html";
$modversion['license'] = "GPL see LICENSE";
$modversion['official'] = 0;
$modversion['image'] = "images/tags_slogo.png";
$modversion['dirname'] = "xbs_tags";
//$modversion['onUninstall'] = "install_funcs.php";
$modversion['onInstall'] = "install_funcs.php";
$modversion['onUpdate'] = "install_funcs.php";

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = "sql/xbs_tags_mysql.sql";
//$modversion['sqlfile']['postgresql'] = "sql/pgsql.sql";

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = TAGS_TBL_TAGS;

// Main Menu
$modversion['hasMain'] = 0;

// Admin menu things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = "admin/index.php";
$modversion['adminmenu'] = "admin/menu.php";

// Configuration items

$modversion['config'][1]['name'] = 'use_title';
$modversion['config'][1]['title'] = '_MI_TAGS_USETITLESNAME';
$modversion['config'][1]['description'] = '_MI_TAGS_USETITLESDESC';
$modversion['config'][1]['formtype'] = 'select';
$modversion['config'][1]['valuetype'] = 'int';
$modversion['config'][1]['default'] = TAGS_CFGMETHODTAGS;
$modversion['config'][1]['options'] = array(
_MI_TAGS_TTL0 => TAGS_CFGMETHODXOOPS,	//Use Xoops
_MI_TAGS_TTL1 => TAGS_CFGMETHODTAGS,	//Use MetaTags
);
$modversion['config'][2]['name'] = 'use_desc';
$modversion['config'][2]['title'] = '_MI_TAGS_USESDESCNAME';
$modversion['config'][2]['description'] = '_MI_TAGS_USEDESCDESC';
$modversion['config'][2]['formtype'] = 'select';
$modversion['config'][2]['valuetype'] = 'int';
$modversion['config'][2]['default'] = TAGS_CFGMETHODTAGS;
$modversion['config'][2]['options'] = array(
_MI_TAGS_DESC0 => TAGS_CFGMETHODXOOPS,	//Use Xoops
_MI_TAGS_DESC1 => TAGS_CFGMETHODTAGS,	//Use MetaTags
);

$modversion['config'][3]['name'] = 'key_method';
$modversion['config'][3]['title'] = '_MI_TAGS_KEYMETHODNAME';
$modversion['config'][3]['description'] = '_MI_TAGS_KEYMETHODDESC';
$modversion['config'][3]['formtype'] = 'select';
$modversion['config'][3]['valuetype'] = 'text';
$modversion['config'][3]['default'] = TAGS_KEYMETHD_3;

$modversion['config'][3]['options'] = array(
_MI_TAGS_KYD0 => TAGS_KEYMETHD_0,  //use database
_MI_TAGS_KYD1 => TAGS_KEYMETHD_1,  //auto text order
_MI_TAGS_KYD2 => TAGS_KEYMETHD_2,  //auto least frequent first
_MI_TAGS_KYD3 => TAGS_KEYMETHD_3,  //auto most frequent first
_MI_TAGS_KYD4 => TAGS_KEYMETHD_4); //use Xoops default keywords

$modversion['config'][4]['name'] = 'max_keys';
$modversion['config'][4]['title'] = '_MI_TAGS_MAXKEYWORDNAME';
$modversion['config'][4]['description'] = '_MI_TAGS_MAXKEYWORDDESC';
$modversion['config'][4]['formtype'] = 'textbox';
$modversion['config'][4]['valuetype'] = 'int';
$modversion['config'][4]['default'] = '30';

$modversion['config'][5]['name'] = 'min_keylen';
$modversion['config'][5]['title'] = '_MI_TAGS_MINKEYWORDNAME';
$modversion['config'][5]['description'] = '_MI_TAGS_MINKEYWORDDESC';
$modversion['config'][5]['formtype'] = 'textbox';
$modversion['config'][5]['valuetype'] = 'int';
$modversion['config'][5]['default'] = '5';

$modversion['config'][6]['name'] = 'track_keys';
$modversion['config'][6]['title'] = '_MI_TAGS_TRKKEYNAME';
$modversion['config'][6]['description'] = '_MI_TAGS_TRKKEYDESC';
$modversion['config'][6]['formtype'] = 'yesno';
$modversion['config'][6]['valuetype'] = 'int';
$modversion['config'][6]['default'] = '1';

$modversion['config'][7]['name'] = 'max_tracks';
$modversion['config'][7]['title'] = '_MI_TAGS_MAXTRKNAME';
$modversion['config'][7]['description'] = '_MI_TAGS_MAXTRKDESC';
$modversion['config'][7]['formtype'] = 'textbox';
$modversion['config'][7]['valuetype'] = 'int';
$modversion['config'][7]['default'] = '10';

//Search things
$modversion['hasSearch'] = 0;

//User comments things
$modversion['hasComments'] = 0;

//Module notification things
$modversion['hasNotification'] = 0;

?>
